INSERT INTO question (id, category, difficulty, question_title, option1, option2, option3, option4, right_answer) VALUES
(1, 'Java', 'Easy', 'What is the size of int in Java?', '4 bytes', '2 bytes', '8 bytes', '16 bytes', '4 bytes'),
(2, 'JavaScript', 'Medium', 'Which type of variable is visible everywhere in a JavaScript function?', 'Local', 'Global', 'Static', 'Block', 'Global'),
(3, 'Python', 'Easy', 'Which of these is a Python data type?', 'integer', 'number', 'char', 'array', 'integer'),
(4, 'Java', 'Hard', 'What is the default value of a boolean in Java?', 'true', 'false', '1', 'null', 'false'),
(5, 'JavaScript', 'Easy', 'Which function is used to parse a string to an integer in JavaScript?', 'parseInt()', 'toString()', 'toInt()', 'int()', 'parseInt()'),
(6, 'Python', 'Medium', 'Which keyword is used to define a function in Python?', 'func', 'def', 'function', 'define', 'def'),
(7, 'Java', 'Medium', 'What does the keyword “super” refer to in Java?', 'A class', 'A method', 'A superclass', 'An interface', 'A superclass'),
(8, 'JavaScript', 'Hard', 'Which is a correct way to create a promise in JavaScript?', 'promise()', 'Promise.all()', 'new Promise()', 'new Promise.all()', 'new Promise()'),
(9, 'Python', 'Hard', 'Which Python library is used for data analysis?', 'NumPy', 'Pandas', 'Matplotlib', 'Scikit-learn', 'Pandas'),
(10, 'Java', 'Easy', 'What is the range of short data type in Java?', '-32,768 to 32,767', '-128 to 127', '0 to 65,535', '-2^31 to 2^31-1', '-32,768 to 32,767'),
(11, 'JavaScript', 'Easy', 'Which method adds an element to the end of an array in JavaScript?', 'push()', 'pop()', 'shift()', 'unshift()', 'push()'),
(12, 'Python', 'Easy', 'How do you start a for loop in Python?', 'for i in range()', 'for (i=0;i<10;i++)', 'foreach', 'loop()', 'for i in range()'),
(13, 'Java', 'Medium', 'What is the use of the “final” keyword in Java?', 'To define a constant', 'To terminate a method', 'To prevent inheritance', 'All of the above', 'All of the above'),
(14, 'JavaScript', 'Medium', 'What will be the output of typeof(null) in JavaScript?', 'object', 'null', 'undefined', 'boolean', 'object'),
(15, 'Python', 'Medium', 'Which of these is not a valid Python keyword?', 'global', 'lambda', 'async', 'volatile', 'volatile'),
(16, 'Java', 'Hard', 'What is method overloading in Java?', 'Same method name with different parameters', 'Same method name in different classes', 'Same method name with same parameters', 'None of the above', 'Same method name with different parameters'),
(17, 'JavaScript', 'Hard', 'What is a closure in JavaScript?', 'A function returned by another function', 'A variable scoped to a function', 'A global variable', 'A block-scoped function', 'A function returned by another function'),
(18, 'Python', 'Hard', 'What is the output of the expression 3 * "Python"?', '"Python"', 'Error', '"PythonPythonPython"', '"3Python"', '"PythonPythonPython"'),
(19, 'Java', 'Medium', 'Which of the following is a marker interface in Java?', 'Serializable', 'Cloneable', 'Both A and B', 'Runnable', 'Both A and B'),
(20, 'JavaScript', 'Easy', 'Which company developed JavaScript?', 'Microsoft', 'Netscape', 'Oracle', 'Google', 'Netscape'),
(21, 'Python', 'Easy', 'What is the keyword used to create a function in Python?', 'function', 'def', 'fun', 'create', 'def'),
(22, 'Java', 'Medium', 'Which of these is not a Java feature?', 'Object-oriented', 'Platform-independent', 'Use of pointers', 'Portable', 'Use of pointers'),
(23, 'JavaScript', 'Easy', 'How do you declare a variable in JavaScript?', 'let', 'var', 'const', 'All of the above', 'All of the above'),
(24, 'Python', 'Medium', 'Which of these is not a built-in data type in Python?', 'list', 'tuple', 'map', 'set', 'map'),
(25, 'Java', 'Hard', 'What is the default encoding used by Java?', 'UTF-8', 'ASCII', 'ISO-8859-1', 'Unicode', 'UTF-8'),
(26, 'JavaScript', 'Medium', 'Which method removes the last element from an array in JavaScript?', 'pop()', 'shift()', 'splice()', 'unshift()', 'pop()'),
(27, 'Python', 'Hard', 'Which of the following is not a valid way to declare a set in Python?', 'set([1, 2, 3])', '{1, 2, 3}', 'set(1, 2, 3)', 'None of the above', 'set(1, 2, 3)'),
(28, 'Java', 'Easy', 'Which of these are not primitive data types in Java?', 'int', 'boolean', 'String', 'char', 'String'),
(29, 'JavaScript', 'Hard', 'What is the output of "0" == 0 in JavaScript?', 'true', 'false', 'undefined', 'null', 'true'),
(30, 'Python', 'Medium', 'What does the function ord() do in Python?', 'Returns the string value of a number', 'Returns the Unicode code of a character', 'Converts a string to a number', 'None of the above', 'Returns the Unicode code of a character'),
(31, 'Java', 'Medium', 'What is the access modifier that makes a member visible to all classes in the same package and all subclasses?', 'public', 'private', 'protected', 'default', 'protected'),
(32, 'JavaScript', 'Easy', 'How do you add a comment in JavaScript?', '// This is a comment', '<!-- This is a comment -->', '/* This is a comment */', '# This is a comment', '// This is a comment'),
(33, 'Python', 'Easy', 'How do you write a single-line comment in Python?', '// This is a comment', '# This is a comment', '/* This is a comment */', '-- This is a comment', '# This is a comment'),
(34, 'Java', 'Hard', 'Which of these is an abstract method in Java?', 'A method without a body', 'A method with the abstract keyword', 'Both A and B', 'None of the above', 'Both A and B'),
(35, 'JavaScript', 'Medium', 'Which operator is used to assign a value in JavaScript?', '=', '==', '===', '!=', '='),
(36, 'Python', 'Hard', 'Which of these is used to handle exceptions in Python?', 'try', 'catch', 'except', 'Both A and C', 'Both A and C'),
(37, 'Java', 'Easy', 'Which loop is used when the number of iterations is known in Java?', 'while', 'for', 'do-while', 'None of the above', 'for'),
(38, 'JavaScript', 'Easy', 'How do you find the length of an array in JavaScript?', 'arr.length()', 'arr.size()', 'arr.length', 'arr.count()', 'arr.length'),
(39, 'Python', 'Medium', 'Which method is used to remove the last item from a list in Python?', 'remove()', 'pop()', 'delete()', 'drop()', 'pop()'),
(40, 'Java', 'Hard', 'Which garbage collection algorithm is used in Java?', 'Mark-Sweep', 'Reference Counting', 'Copying', 'All of the above', 'Mark-Sweep');
--resting the id
ALTER TABLE question ALTER COLUMN id RESTART WITH 41;